spring:
  application:
    name: camp-reservation
  security:
    #oauth2:
     # client:
       # registration:
        # google:
        #   client-id:
        #   client-secret:
        #   scope:
        #     - profile
        #     - email
        #   redirect-uri: "{baseUrl}/login/oauth2/code/google"
        # kakao:
        #   client-id:
        #   client-secret:
        #   redirect-uri: "http://localhost:8080/login/oauth2/code/kakao"
        #   client-authentication-method: client_secret_post
        #   authorization-grant-type: authorization_code
        #   scope:
        #     - profile_nickname
        #     - account_email
        #   client-name: kakao
        # naver:
        #   client-id:
        #   client-secret:
        #   redirect-uri: "{baseUrl}/login/oauth2/code/naver"
        #   authorization-grant-type: authorization_code
        #   client-name: Naver
        #   scope:
        #     - name
        #     - email

        # provider:
        #   google:
        #     authorization-uri: https://accounts.google.com/o/oauth2/auth
        #     token-uri: https://oauth2.googleapis.com/token
        #     user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
        #   kakao:
        #     authorization-uri: https://kauth.kakao.com/oauth/authorize
        #     token-uri: https://kauth.kakao.com/oauth/token
        #     user-info-uri: https://kapi.kakao.com/v2/user/me
        #     user-name-attribute: id
        #   naver:
        #     authorization-uri: https://nid.naver.com/oauth2.0/authorize
        #     token-uri: https://nid.naver.com/oauth2.0/token
        #     user-info-uri: https://openapi.naver.com/v1/nid/me
        #     user-name-attribute: response

  sql:
    init:
      platform: mysql
      mode: always
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3307/campReserve?serverTime=UTC&characterEncoding=UTF-8
    username: root
    password: qwer1234
  jpa:
    hibernate:
      ddl-auto: update
      #ddl-auto: create
      show-sql: true  # Hibernate SQL 출력 활성화
      format_sql: true  # SQL 쿼리 형식화
      use_sql_comments: true  # SQL 쿼리에 주석 추가 (테이블, 컬럼 등)
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    generate-ddl: false
    database-platform: org.hibernate.dialect.MySQL8Dialect
    open-in-view: false  # JPA 트랜잭션을 뷰 렌더링 중에 열지 않도록 설정
